 export const REQ_START='REQ_START';
 export const REQ_SUCCESS='REQ_SUCCESS';
 export const REQ_FAIL='REQ_FAIL';

 export const SEC_REQ_SUCCESS='SEC_REQ_SUCCESS'
 
 export const ORDER_OPTIONS_SUCCESS='ORDER_OPTIONS_SUCCESS'

 export const SERIES_REQ_SUCCESS='SERIES_REQ_SUCCESS'
 export const SERIES_REQ_FAIL='SERIES_REQ_FAIL'

 export const ORDER_SERIES_OPTIONS_SUCCESS='ORDER_SERIES_OPTIONS_SUCCESS'
 
